In [ ]:
##################################################

In [ ]:
#####################Computer Vision Project ############## 

In [9]:
import cv2
import numpy as np

In [10]:
rimg = cv2.imread("./images/2.jpeg")
rimg_gray = cv2.cvtColor(rimg,cv2.COLOR_BGR2GRAY)
# rims=cv2.resize(img1,(960,540))
limg=cv2.imread("./images/1.jpeg")
limg_gray = cv2.cvtColor(limg,cv2.COLOR_BGR2GRAY)
# lims=cv2.resize(img2,(960,540))
sift = cv2.xfeatures2d.SIFT_create()

kp1, des1 = sift.detectAndCompute(rimg_gray,None)
kp2, des2 = sift.detectAndCompute(limg_gray,None)

for d in des1:
    print(d)

[  9.   3.   0.   0.   0.   0.   0.   1. 137.   2.   0.   0.   0.   0.
   0.  22. 160.   8.   9.   1.   1.   3.   1.  56.  13.  14.  17.  12.
  31.  23.   7.   5.  11.   1.   0.   0.   0.   0.   0.   3. 160.  18.
   0.   0.   0.   0.   0.   3. 160.  33.   1.   5.   8.  25.   8.  22.
  51.  21.   8.  12.  16.  41.  12.  24.   9.   0.   0.   0.   0.   0.
   0.   4. 160.   3.   0.   0.   0.   0.   0.  20. 160.  16.   1.  17.
  32.  18.   4.  57.  23.  65.  32.  49.  66.  35.   3.   6.  10.   0.
   0.   0.   0.   0.   0.   2. 148.  15.   0.   0.   0.   0.   0.   4.
 160.  43.   0.   0.  15.  36.   5.  21.  21.  10.   2.   2.  42. 160.
  19.   9.]
[ 59.   4.   0.   0.   0.   0.   0.   2. 164.  22.   0.   3.   4.   8.
   3.  14.  57.  20.   8.  19.  20.  34.   8.  18.  29.  14.   7.  51.
  49.  41.   9.  18.  78.   1.   0.   0.   0.   0.   0.   9. 164.  10.
   0.   5.  16.  13.   3.  56.  42.  51.  22.  42.  91.  66.   4.  11.
  11.  52.  29. 107.  64.  26.  10.   3.  74.   7.   0.   0.   0.

   5.   5.]
[ 10.   2.  11.  97.   0.   0.   3.  37.   1.   5.  42. 121.   4.   2.
  16.   6.  24.  36.  25.  34.   2.   1.  25.  24.  52.  17.   4.   0.
   0.   0.  10.  68.  17.   5.  12. 121.  17.   0.   0.   9.  81.   9.
   7.  45.   6.   9. 114. 121.  20.  12.   5.   6.  59.  69. 121.  57.
  44.  63.  27.   4.  18.  10.  22.  47.  46.   9.   3.  62.  31.   2.
  10.  19. 121. 102.   9.   7.   5.   4.  14.  58.  36.  38.  11.  18.
  92.  58.  81.  41.   7.   6.   2.   2.  17.  17. 121. 121.  11.   1.
   0.   3.   9.   5.  41.  83.  68.  43.   5.   4.   7.   5.  33.  48.
  44. 121.  31.   2.   1.   1.  14.  19.   6.  70.  33.   9.   3.   1.
  19.  24.]
[120.  58.   4.  11.   3.   0.   0.   1. 120. 107.   9.   3.  11.  47.
   4.   7.   1.   6.   5.  15.  72. 120.  15.   1.  45.   4.   0.   8.
  26.  21.   8.  16. 114.  46.   3.   5.   4.  24.  24.  25. 120.  99.
   6.   2.   7.   4.   2.  31.  21.  10.   5.  27. 120.  51.  10.  13.
  36.   0.   0.  12.  40.  17.  23.  98.  37.  26.  2

  28.  33.]
[ 28.   5.   0.   1.  30.  21.   9.   7. 123.  73.   7.   2.   5.  14.
   8.  30.  17.  23.  12.  13. 116. 123.   6.   7.   0.   0.   0.   0.
  74. 123.   2.   0.  11.   2.   0.   0.   8.  38.  66.  24.  60. 116.
  15.   2.   8.  52.  38.   8.  82.  77.  24.  14.  53.  62.  13.  21.
   2.   0.   0.   0.  47. 123.  23.   4.  15.   2.   3.   8.  15.  27.
  55.  37.  34.  12.   6.  41.  60.  53.  11.   8. 123. 106.   3.   2.
   6.  31.  11.  27.  14.  39.   2.   0.  19. 123.  23.   5.   0.   1.
   2.   5.  98.  76.  32.   2.   2.   8.   6.  27.  72.  36.   1.   0.
  21. 123.  20.   3.   5.   8.   9.   1.  56. 123.   4.   0.   8.  32.
   8.   5.]
[ 15.  17.  13.  49. 104.  15.   3.   6.  29.   4.   0.  17.  94.  18.
   3.   9. 121.  19.   0.   0.  15.  14.   5.  45.  12.   1.   0.   0.
 121.  91.   3.   8.   4.   8.  10.  50.  73.  16.   6.   2.  48.   1.
   0.  11.  42.  42.  14.  22. 121.  26.   3.   3.  17.  20.  13. 121.
  12.   4.   3.   9. 121. 114.   9.  18.   2.   0.   

   8.  42.]
[  4.   8.   4.   7.   8.  17.  13.  14.  26.   0.   0.   7.   8.  10.
  27. 122.  27.   0.   0.   1.  26.  63.  47.  92.   1.   0.   0.   1.
  31.  72.  51.  21.  20.   6.   7.  27.  11.  17.  19.  17. 138.  25.
   6.  14.  12.  15.  51. 138.  26.   7.   6. 109. 138.  82.  80.  92.
  35.  40.  10.  40.  41.  20.  18.  17.  35.  19.   9.  56.  37.   4.
   4.   1. 138. 138.  60.  59.   9.   1.   2.  16.  24.  35.  54. 138.
 138.   4.   8.  19.  23.  38.   6.  26.  21.   4.  23.  32.   8.   2.
   0.   4.  27.  15.  54.  21.  50.  41.  15.  11.   4.  12.  40.  18.
  14.  13.  19.  34.  15.   4.   3.  13.   7.   8.  21.  18.   7.   4.
  10.  15.]
[  9.   6.   6.  13.   6.   6.  12.  11.  13.   8.  15.  13.  19.  40.
  20.  19.   9.   6.  30.  29.  21.  74.  13.   5.  77.  39.   5.   2.
   0.   2.   1.   8.  38.   6.   7.  41.  27.   9.   8.  13. 142.  11.
   1.   8.  21.  77.  65. 142.  20.   3.   1.   6. 142. 142.  55.  36.
  39.  13.   7.   9.  12.  18.   5.  31.  43.   4.   

   0.   3.]
[  4.  18.  65.  26.  31.  10.   1.   4.  34.  46.  21.  15.   7.   2.
   1.  11.   5.  15.  65.  97.  24.   4.   1.   1.  24.  92.  47.  13.
   2.   2.   2.   4.  12.  67. 114.  46.  52.  28.   0.   1. 112. 119.
  34.  11.  16.   6.   0.   3.  22.  18.  16.  54.  80.  58.  24.  20.
  41.  45.  17.  15.  10.  10.  39.  60.  30.   9.   2.   7. 118. 119.
   7.  24. 119.  22.   1.  14.  39.  10.   5.  88.  25.  51.  48.  99.
 119.   6.   3.   9.   7.  83. 119.  46.  11.   2.   8.  10.  10.   0.
   1.  12.  45.  43.  23.  32.  76.   0.   0.  10.  69.   8.  11.  84.
   5.   8.   9.  43. 119.   6.   1.   5.   7.  21.  40.  18.  20.   3.
   2.   8.]
[ 17.  80.  87.  21.   2.   0.   0.   1.  78. 128.  51.  11.   3.   0.
   0.   2.  12.  19.  47.  58.  17.  10.   4.   1.  10.  27.  45.  16.
   1.   3.   6.   8.  43.  15.   9.  18.  12.  11.  21.  12. 128.  33.
   4.   9.  17.   3.   5.  16.  53.  24.  23.  98. 106.   0.   0.   2.
  71.  58.  21.  18.   4.   0.   1.  29.  16.   1.   

  28.  14.]
[  0.   1.  25. 121. 100.   2.   0.   0.  20.  30.  19. 121.  92.   4.
   0.   2.  48.  51.  26.  32.  38.  33.   7.  18.   0.   3.   8.  31.
  67.  85.   2.   1.  14.  13.  18.  42.  97.  90.   1.   2.  47.   6.
   1.  17.  89. 121.   5.   8. 121.  16.   0.   0.  12.  59.  14.  36.
  12.   0.   0.   0.  88. 121.   6.   5.  45.  16.   1.   8.  43.  44.
   5.  17.  12.   1.   0.   4. 100. 121.  11.   9. 121.  32.   7.   6.
  15.  35.  11.  30.  21.  10.  14.  29. 110.  84.   1.   3.   3.   0.
   0.   2.  15.  46.  20.  16.   1.   0.   0.   1.  49. 121.   5.   0.
  29.  26.   8.  11.  26.  52.  10.   4.   3.   7.  31.  58.  30.  15.
   2.   0.]
[101.   8.   0.   0.   0.   0.   0.  11. 152.  29.   2.   5.   6.   0.
   1.  40.  38.   8.  12.  14.  13.   1.   3.  35.  22.   3.   2.   0.
   2.   3.  16.  48.  92.  27.   0.   0.   0.   0.   0.   1. 152.  88.
   1.   1.   2.   0.   8.  20.  64.   4.   0.   2.   3.   2.  39.  67.
  42.   0.   1.   4.   2.   0.   7.  43.  77.   3.   

   0.   2.]
[ 21.   0.   0.   0.   2.   7. 109. 102. 139.   5.   1.   2.   1.   4.
  19. 112.  49.   4.   4.  48.  23.   1.   1.  16.   1.   1.   1.  16.
  66.  35.  12.   3.  19.   7.   4.  80.  66.  22.  71. 103. 139.  50.
   7.  34.  25.  10.  12.  16.  68.  14.   6.  34.  37.  27.   6.   7.
  47.   8.   2.   3.  46.  34.  18.  16.  40.   6.   5. 139.  87.   1.
   1.  26. 139.  19.   5.  32.  10.   2.   1.  81.  65.   2.   1.   3.
  11.  46.  20.  26.  28.   3.   1.   0.  39.  16.  13.  28.  29.   0.
   0.  52.  62.   5.  13. 111. 139.   1.   0.   3.   6.   1.   3. 139.
  21.  12.   8.  22.  32.   2.   1.  13.  18.  23.   4.   5.  26.   2.
   1.   4.]
[  9.  12.  89.  40.  21.   2.   0.   1.  60. 134.  55.   4.   1.   0.
   1.  14. 135. 139.   3.   0.   0.   3.   9.  16.  59.  31.   0.   0.
   7.  19.  31.  15.  15.  23.   5.   5.  28.   9.  13.  11.  77.  67.
   3.   1.   4.  12.  25.  19. 139.  79.   2.   0.   0.   0.   0.  39.
 133.  62.  14.   6.   5.   4.   0.  10.  29.  51.  1

In [11]:
#Brute force matching
bf=cv2.BFMatcher(cv2.NORM_L1, crossCheck=True)
matches = bf.match(des1,des2)
matches = sorted(matches,key=lambda x:x.distance)
#minimum distance implies good matching !
for m in matches:
    print(m.distance)

125.0
136.0
148.0
151.0
156.0
158.0
162.0
166.0
168.0
175.0
176.0
181.0
181.0
192.0
198.0
198.0
198.0
200.0
200.0
211.0
212.0
213.0
214.0
216.0
218.0
218.0
220.0
223.0
224.0
225.0
226.0
227.0
230.0
231.0
232.0
233.0
234.0
235.0
236.0
237.0
238.0
239.0
240.0
240.0
242.0
243.0
245.0
245.0
246.0
247.0
249.0
252.0
253.0
253.0
254.0
258.0
261.0
262.0
262.0
265.0
266.0
267.0
268.0
269.0
270.0
270.0
271.0
271.0
271.0
272.0
274.0
274.0
275.0
276.0
277.0
278.0
280.0
280.0
282.0
282.0
283.0
284.0
285.0
286.0
287.0
287.0
288.0
289.0
291.0
292.0
293.0
294.0
296.0
299.0
303.0
303.0
304.0
304.0
307.0
307.0
309.0
310.0
311.0
315.0
319.0
319.0
320.0
320.0
320.0
320.0
322.0
322.0
323.0
324.0
324.0
326.0
329.0
330.0
330.0
330.0
332.0
334.0
335.0
337.0
338.0
338.0
338.0
339.0
339.0
341.0
341.0
345.0
346.0
346.0
346.0
347.0
348.0
349.0
349.0
350.0
351.0
352.0
353.0
353.0
354.0
354.0
354.0
354.0
355.0
356.0
358.0
360.0
362.0
362.0
362.0
362.0
363.0
363.0
364.0
366.0
367.0
367.0
369.0
370.0
371.0
371.0
371.

In [12]:
matching_result = cv2.drawMatches(rimg_gray,kp1,limg_gray,kp2,matches[:20],None,flags=2)
#ims1=cv2.drawKeypoints(ims1,keypoints,None)
cv2.imshow("Matching Result",matching_result)
cv2.imshow("right image",rimg_gray)
cv2.imshow("left image",limg_gray)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [13]:
good = []
for m in matches[:20]:
    good.append(m)
#print(good,3*'\n',kp1,4*'\n')
# for m in good :
#     src_points.append(np.float32(kp1[m.queryIdx].pt))
# print(src_points)
# x=src_points.reshape(-1,1,2)
# print(2*'\n',x)
src_pts = np.float32([ kp1[m.queryIdx].pt for m in good ]).reshape(-1,1,2)
dst_pts = np.float32([ kp2[m.trainIdx].pt for m in good ]).reshape(-1,1,2)
M,mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)
print(M)
h,w = rimg_gray.shape
print(h,w)


[[ 8.83884849e-01  6.06078650e-02  1.44490546e+02]
 [-9.18368064e-02  9.77031460e-01 -1.17854765e+01]
 [-3.19412919e-04  5.47204318e-05  1.00000000e+00]]
300 400


In [14]:
pts = np.float32([ [0,0],[0,h-1],[w-1,h-1],[w-1,0] ]).reshape(-1,1,2)
dst=cv2.perspectiveTransform(pts,M)
print(pts,2*'\n',dst)
# lims=cv2.polylines(lims,[np.int32(dst)])

[[[  0.   0.]]

 [[  0. 299.]]

 [[399. 299.]]

 [[399.   0.]]] 

 [[[144.49054  -11.785477]]

 [[159.99457  275.8339  ]]

 [[579.6752   274.15878 ]]

 [[569.7761   -55.501835]]]


In [15]:
limg_gray=cv2.polylines(limg_gray,[np.int32(dst)],True,255,5,cv2.LINE_AA)
cv2.imshow("original image overlapping",limg_gray)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [16]:
final_image=cv2.warpPerspective(rimg,M,(limg.shape[1]+rimg.shape[1],limg.shape[0]))
final_image[0:limg.shape[0],0:limg.shape[1]]=limg
print(final_image[0].shape,10*'\n',final_image)
cv2.imshow("final stichhed image",final_image)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()


(800, 3) 









 [[[212 194 187]
  [168 142 125]
  [184 151 125]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[185 144 121]
  [113  64  32]
  [116  60  19]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[185 146 124]
  [107  62  29]
  [115  60  21]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[120 131 129]
  [ 21  32  30]
  [ 21  29  29]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[121 132 130]
  [ 23  34  32]
  [ 22  30  30]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[121 132 130]
  [ 22  33  31]
  [ 20  30  30]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [35]:
#trimming the black space !!!
# def trim(frame):
#     #crop top
#     if not np.sum(frame[0]):
#         return trim(frame[1:])
#     #crop top
#     if not np.sum(frame[-1]):
#         return trim(frame[:-2])
#     #crop top
#     if not np.sum(frame[:,0]):
#         return trim(frame[:,1:])
#     #crop top
#     if not np.sum(frame[:,-1]):
#         return trim(frame[:,:-2])
#     return frame

In [36]:
# cv2.imshow("original_image_stitched_crop.jpg", trim(final_image))
# k=cv2.waitKey(0)
# if k==27:
#     cv2.destroyAllWindows()